name: Install Environment via Conda and Test

on: [push]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Update conda
      run: |
        conda update conda
    - name: Install dependencies
      run: |
        conda env update --file env.yaml --name base
    - name: Test with pytest
      run: |
        python -m pytest test/
